version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10.0

jobs:
  publish:
    <<: *defaults
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - '5a:4e:7c:31:29:12:34:d2:a3:bc:43:0f:4c:fa:09:c5'

      - restore_cache:
          keys:
            - v0-build-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install package.json dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v0-build-dependencies-{{ checksum "package.json" }}

      - run:
          name: Configure dependencies
          command: |
            git config --global user.email "sampjon+ci-build@gmail.com"
            git config --global user.name "ci-build"

      - run:
          name: Deploy
          command: CI=false yarn deploy

workflows:
  version: 2
  main:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
